name: GitHub Actions
on: [push]
jobs:
  Pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Adjust Ruby version if needed
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Serve Jekyll
        run: bundle exec jekyll serve --trace --destination public
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
